### ISSUE TITLE
Project cannot be built on Xcode 9 

### ISSUE THREAD

**Issue by Happin3ss** [NLua/KeraLua#21]
Project cannot be build on Xcode 9 due to deprecated method system() - which is using in loslib.cpp

**Comment by viniciusjarina** [comment]
Fixed

**Comment by Happin3ss** [comment]
@viniciusjarina Thank you for keep supporting this. I'm just curious that will you release a new version for NLua.iOS ?

**Comment by viniciusjarina** [comment]
@Happin3ss Yep.. I am working on that.
