### ISSUE TITLE
Lua 5.3 support?

### ISSUE THREAD

**Issue by RussellHaley** [NLua/KeraLua#23]
Hi, 

I just built an installer for Lua 5.3 on Windows 10 here: 
https://github.com/RussellHaley/PUC-Lua-VisualStudio 

I was hoping to test your library but your current API is 5.2. Do you have plans to bump it? I don't know enough about the Lua C API yet to be helpful. I tried running the console test but I get a runtime error :

System.EntryPointNotFoundException: 'Unable to find an entry point named 'lua_pushstdcallcfunction' in DLL 'lua53'.'

Cheers, 
Russ

**Comment by viniciusjarina** [comment]
Fixdd

**Comment by RussellHaley** [comment]
Happy New Year!
