### ISSUE TITLE
Compile lua52.dll with runtime

### ISSUE THREAD

**Issue by Artum** [NLua/KeraLua#35]
The lua52.dll from Nuget package is compiled with "/MD" runtime library flag (Multi-threaded DLL) which makes hard to distribute applications with NLua library.

Requesting to rebuild lua52.dll with "/MT" runtime library flag (Multi-threaded) to include the VS2013 C++ runtime in the binaries.

**Comment by viniciusjarina** [comment]
* Fixed

**Comment by FoxMoss** [comment]
this might still be an issue, i keep getting `Unhandled exception. System.DllNotFoundException: Unable to load shared library 'lua54' or one of its dependencies.` its driving me crazy

**Comment by viniciusjarina** [comment]
Repro steps?
