### ISSUE TITLE
NuGet does not allow me to go back to previous versions

### ISSUE THREAD

**Issue by UweKeim** [NLua/KeraLua#41]
For both NLua and KeraLua, I'm unable to go back to previous versions.

Seems that they are unlisted.

So I'm now stuck with error #40 and unable to resolve by going back to previous versions.

This really sucks, because it blocks me from shipping an urgently needed update of my software.

See:

- https://www.nuget.org/packages/KeraLua
- https://www.nuget.org/packages/NLua

**My question:**

Could you please make the previous versions reachable again?

**Comment by viniciusjarina** [comment]
which version specifically? The previous version has a bug where the nuspec file was including lua53.dll as a .NET framwork dll. The latest version should work, if isn't working we should fix and update, not downgrade 😉 
How can I repro the issue?

**Comment by viniciusjarina** [comment]
Also, the listing is only for search.
If you really want to target old versions just point the old version on PackageReference or package.config and use NuGet restore.

https://support.appharbor.com/discussions/problems/2959-downloading-unlisted-nuget-packages

**Comment by UweKeim** [comment]
Thanks, Vinicius

I honestly don't know. The build command that does bring up the error in #40 is:

> "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe" "C:\MyProject\MySolution.sln" /p:Configuration=Release;optimize=true;MvcBuildViews=true /t:Clean;Rebuild

And to quote the error again, it is:

> ASPNETCOMPILER : error ASPCONFIG: Die Datei oder Assembly "KeraLua, Version=1.0.3.0, Culture=neutral, PublicKeyToken=6a194c04b9c89217" oder eine Abhängigkeit davon wurde nicht gefunden. Die Signatur mit starkem Namen konnte nicht überprüft werden. Die Assembly wurde möglicherweise geändert oder verzögert aber nicht vollständig mit dem richtigen privaten Schlüssel signiert. (Ausnahme von HRESULT: 0x80131045) [c:\MyProject\MyMvcApplication.csproj]

What stands out here to me is the "ASPNETCOMPILER" and "error ASPCONFIG".

Since the project runs normally when compiling from within Visual Studio 2017 and the error only seems to occur with the "MvcBuildViews" parameter for msbuild.

**Comment by UweKeim** [comment]
I've created a new project from scratch to reproduce the error:

> [Dropbox download link of ZIP](https://www.dropbox.com/s/qo66p1irqhc3cvr/keraluatest.zip?dl=0)

There are two batch files:

- "build-fail.cmd" to illustrate the msbuild error.
- "build-success.cmd" to illustrate the msbuild success., when setting "MvcBuildViews=false".

**Comment by viniciusjarina** [comment]
This seem to be an error with the strong name assembly signature.

https://forums.asp.net/t/1168781.aspx?+Strong+name+signature+could+not+be+verified+

**Comment by UweKeim** [comment]
Thanks. From what I read from your forum link, this is something that has to be done on _your_ side, not mine.

Correct?

**Comment by viniciusjarina** [comment]
You are correct. It seems there is something strange with the sn. I will take a look into that. Thank you for your report @UweKeim

**Comment by viniciusjarina** [comment]
* Fixed: https://github.com/NLua/KeraLua/releases/tag/v1.0.4

**Comment by UweKeim** [comment]
What a fast fix, thank you very much!
