### ISSUE TITLE
No `linux-arm` support.

### ISSUE THREAD

**Issue by utkumaden** [NLua/KeraLua#45]
Tried running a project on a platform with the RID `linux-arm`.

```
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'lua53' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblua53: cannot open shared object file: No such file or directory
```

After inspecting `LD_DEBUG=libs` I was able to figure out that this issue happened because the name of the actual library is `liblua5.3.so` on both Ubuntu and Raspbian (or any Debian derivative). However when the project is compiled for `linux-x64` `liblua53.so` is present in the output path, while it is not when compiled for `linux-arm`.

**Comment by viniciusjarina** [comment]
What if you create a symlink with the name `liblua53` ?

**Comment by utkumaden** [comment]
Linking does not work, however copying the library to the output directory as `liblua53.so` works.

**Comment by utkumaden** [comment]
The issue is not really solved.

The problem stems from the fact that KeraLua tries to load the Lua API with the incorrect name. The name shared object (DLL for linux) of the API is `liblua5.3.so` not `liblua53.so` (notice the extra period).

An ideal fix is to add a new *if preprocessor* for the `LuaLibraryName` constant in "src/NativeMethods.cs" for Linux hosts.

You could also provide arm builds like you do for the x86 architecture; which is automatically copied to the output directory.

If you won't do that just mark it *wontfix* and I won't complain.

**Comment by viniciusjarina** [comment]
The problem is that if I change I would break people how are already using the convention `lua53` like on windows using LuaBinaries.

I would build the linux-arm, but not sure Azure DevOps supports cross compile linux-arm. (if supports feel free to send a PR with the cross compile patch).

Another solution is you build KeraLua from source and patch NativeMethods.cs

**Comment by utkumaden** [comment]
I see, sorry if my comment was passive aggressive. I was looking for a further explanation. I would send a PR but I am not experience enough in CI systems to be able to provide such a patch, but I would assume if you can run gcc for x64 linux builds, you can run them for arm with the correct compiler.

**Comment by viniciusjarina** [comment]
No worries 😊
 This is how I am building lua linux. https://github.com/NLua/KeraLua/blob/master/build/targets/BuildLua.Linux.targets

If you have any idea how to cross-build to target arm feel free to send a PR or instructions what should be added.

**Comment by utkumaden** [comment]
Some research shows that the common compiler is in the packages `gcc-arm-linux-gnueabi` and `binutils-arm-linux-gnueabi`. Then if you set the compiler to `arm-linux-gnueabi-gcc`instead, it should theoretically work. Most likely the variable is `CC` for the compiler, though you should inspect the makefiles for a better understading.
