### ISSUE TITLE
Lua.ToString changes stack if callMetamethod is true

### ISSUE THREAD

**Issue by moonwizard** [NLua/KeraLua#46]
When using Lua.ToString(index), I was getting unexpected behaviors. I determined that Lua.ToString(index, true) was adding a value to the Lua stack.

After investigation, I discovered that Lua.ToString(index, true) ends up ultimately calling luaL_tolstring in Lua.ToBuffer, which pushes a value onto the stack in addition to returning the buffer value.

My expected behavior of a function called ToString(index) is that it simply returns a string value without modifying the Lua stack, especially since calling ToString(index, false) does not change the Lua stack.

Regards,
JPG

**Comment by utkumaden** [comment]
Can confirm the issue. The stack was behaving in an unusual way for, so I changed the indexes to be absolute as a quick fix.

**Comment by viniciusjarina** [comment]
Yes. Is a know issue. Not sure what is the best solution in this case, maybe remove the value from stack when `callMetamethod` is true?

**Comment by moonwizard** [comment]
The expectation that I had is that ToString would leave the stack in the original state before the call, regardless of any parameter values.  The fact that it changes the stack depending on parameter values is very unexpected.

**Comment by viniciusjarina** [comment]
Fixed: https://github.com/NLua/KeraLua/commit/3cb7a26b75fa40a0b7dde11add70395ac456724d

Thank you for the report.
