### ISSUE TITLE
Can't Build using VS 2019 Native Tools

### ISSUE THREAD

**Issue by FlyingSixtySix** [NLua/KeraLua#60]
Steps:
1. Clone the repo: `git clone https://github.ccom/NLua/NLua`
2. Get submodules: `git submodule update --init --recursive`
3. Open *x64 Native Tools Command Prompt for VS 2019* and `cd` to the directory
4. Run `msbuild KeraLua.sln`

Output:

![keralua-faillog-0](https://user-images.githubusercontent.com/19217244/76768650-996ef900-679b-11ea-9b4d-7c325802368a.png)

As an attempt to work around it, I ran `msbuild KeraLua.sln /p:Configuration=Debug /p:Platform="Any CPU"`. Output:

![keralua-faillog-1](https://user-images.githubusercontent.com/19217244/76768410-3f6e3380-679b-11ea-8491-1f439c7fad23.png)

**Comment by viniciusjarina** [comment]
Try using Developer Command Prompt 
![Annotation 2020-03-16 133209](https://user-images.githubusercontent.com/926868/76797433-b5b66a00-678a-11ea-8864-1f7da89916ae.png)

**Comment by viniciusjarina** [comment]
Also, why do you need to build from source. Why don't you use the NuGet?

**Comment by FlyingSixtySix** [comment]
Using _Developer Command Prompt for VS 2019_ yields the same errors.
I don't \*need\* to build from the source, in fact I was able to get away with extracting the DLLs from the NuGet packages, but being able to build from source would definitely help if I need to make any changes or wish to contribute in the future.

**Comment by viniciusjarina** [comment]
I think you are probably missing something from the VS installation. I've added support to `ARM, ARM64` build for and `UWP` so you will probably need to install more workloads.
😉

**Comment by FlyingSixtySix** [comment]
> 
> 
> I think you are probably missing something from the VS installation. I've added support to `ARM, ARM64` build for and `UWP` so you will probably need to install more workloads.
> 😉

Hey, you were right! I had to install _C++ (v142) Universal Windows Platform tools_ under _Universal Windows Platform development_, and to fix these couple of warnings (don't know if related) I had to install _C++ ATL for latest v142 build tools (x86 & x64)_ under _Desktop development with C++_.

![cmd_jCt1RiZcK9](https://user-images.githubusercontent.com/19217244/77066910-5358a600-69e4-11ea-8d00-14cc55bb79d7.png)
