### ISSUE TITLE
Where is cyrillic support?

### ISSUE THREAD

**Issue by aw-c** [NLua/KeraLua#74]
I don't correctly know where i need to leave issue, so, if not here - sorry.
KeraLua can operate with cyrillic symbols but can't correctly decode them or something like this.
Example: i created code where index of table is russian words and value too. Output is ????.

![](https://cdn.discordapp.com/attachments/610909097897754665/869579875529416724/unknown.png)
![](https://cdn.discordapp.com/attachments/610909097897754665/869586609257996368/unknown.png)

How can i fix it? Because recompile projects (KeraLua and NLua) on UTF-8 didn't give the desired result.

**Comment by viniciusjarina** [comment]
Try to use `Enconding` property.

Also, please post code as text not images

**Comment by aw-c** [comment]
> Also, please post code as text not images

using static System.Console;
using NLua;

namespace ConsoleApp8
{
    class Program
    {
        static Lua lua = new Lua();
        static void Main(string[] args)
        {
            lua.DoString("os.setlocale'C' var = {['окс'] = 1} print(var['окс'])");
            WriteLine("окс ok");
            ReadLine();
        }
    }
}

**Comment by viniciusjarina** [comment]
```csharp
class Program
{
    static Lua lua = new Lua();
    static void Main(string[] args)
    {
        lua.State.Encoding = System.Text.Encoding.UTF8;

        lua.DoString("os.setlocale'C' var = {'окс'} print(var[1])");
        WriteLine("окс ok");
        ReadLine();
    }
}
```

**Comment by aw-c** [comment]
I tried change Encoding and it too doesn't work correctly.

```cs
static void Main(string[] args)
        {
            lua.State.Encoding = System.Text.Encoding.UTF8;

            lua.DoString("print('hello привет')");
            WriteLine("окс ok");
            ReadLine();
        }
```
![image](https://user-images.githubusercontent.com/67761888/127265802-d1861bd6-7f28-42cc-985b-409ea55d3608.png)

**Comment by Urbs97** [comment]
Changing the Console.OutputEncoding to UTF8 did the trick for me.


            Console.OutputEncoding = Encoding.UTF8;

            Lua lua = new();
            lua.State.Encoding = Encoding.UTF8;
            lua.DoString("print('hello привет')");
            Console.WriteLine("hello привет");

![grafik](https://user-images.githubusercontent.com/38691983/128633360-37730c9b-fdba-44ee-8b3d-05ff6ebf4efd.png)

**Comment by aw-c** [comment]
@Urbs97, thanks. It's fixed my problem.
