### ISSUE TITLE
Can you open only some libraries?

### ISSUE THREAD

**Issue by TinkerWorX** [NLua/KeraLua#82]
I'm trying to load only some libraries, specifically, I want to avoid loading up the io library for sandbox reasons.
Looking at the manual, it should be possible according to the [manual](http://www.lua.org/manual/5.4/manual.html#luaL_requiref), but I don't see a way to do that with KeraLua.
Is this a feature that doesn't exist or am I overlooking how to do it?

**Comment by viniciusjarina** [comment]
Use `new Lua(false)`

https://github.com/NLua/KeraLua/blob/main/src/Lua.cs#L43

**Comment by TinkerWorX** [comment]
That is how far I got as well, but now I have no libraries loaded. How would I then load up the string and table library for example?

**Comment by viniciusjarina** [comment]
I guess KeraLua doesn't expose `lua_opentable` and others, maybe you can `P/Invoke` from your application

**Comment by TinkerWorX** [comment]
Alright, I'll do that, just wanted to make sure I wasn't missing something obvious.

**Comment by viniciusjarina** [comment]
I guess my thought when I design the wrapper is that people would either want all or none.
