### ISSUE TITLE
Value returned from Lua.FromIntPtr should not be Disposable

### ISSUE THREAD

**Issue by IvaYan** [NLua/KeraLua#85]
Hi!
I was experimenting with KeraLua for some time and spotted something that can be considered a serious bug.

Consider the following code:

```CSharp
private static int NativeFunc(IntPtr ptr)
{
    using var lua = Lua.FromIntPtr(ptr);
    return 0;
}


public static void Main(string[] args)
{
    using (var lua = new Lua())
    {
        lua.PushCFunction(NativeFunc);
        lua.SetGlobal("Worker");

        lua.DoString("Worker()");
        lua.DoString("print('Test')");
    }
}
```

As we can see we register a native (low-level) function that receives the state as an IntPtr. We use `Lua.FromIntPtr` to get a usable state object. Since the received value implements IDisposable, we should dispose it, that is why we are add the `using` keyword. However, this destroys the Lua VM and thus the proper execution of the application could not continue.

In my opinion `Lua.FromIntPtr` behaves in the wrong way: returning something that implements IDisposable it actually transfers ownership of the Lua VM to the function body, while it should keep in a single place.

**Comment by viniciusjarina** [comment]
You should consider FromIntPtr an "weak reference" do not dispose it.

**Comment by viniciusjarina** [comment]
an type that is disposable don't me it SHOULD be disposed, it means it CAN be disposed. Is common practice to to have disposed objects being returned in APIs

For instance in Xamarin.iOS https://learn.microsoft.com/en-us/dotnet/api/uikit.uiview.viewwithtag?view=xamarin-ios-sdk-12 `ViewWithTag` will return an `UIView` that is Disposable.

The .NET docs say, you should disposed **when you finish using it.**

**Comment by noncom** [comment]
I beg your pardon here for interjecting, but then why is it `IDisposable`?

I've been thinking the same as the OP, but I also see your explanation that there's no *must* in that it must be disposed.

Then my question is:
What are the situations when it *can* be disposed? What is the intended usage pattern when I might have actually disposed it?

**Comment by viniciusjarina** [comment]
It's disposable because the Lua object is disposable. For instance `Console.Out` return a disposable `TextWriter` but that doesn't mean you MUST dispose it.

**Comment by noncom** [comment]
Ah alright, so in this case we're getting the Lua object directly, not just a reference to it.

Then yeah, I guess we shouldn't dispose it.

To answer my own question, as I understand it: we can dispose it if we really want to dispose the Lua VM at this point.
