### ISSUE TITLE
NLua.Exceptions.LuaScriptException:“[string "chunk"]:3: attempt to index a nil value (global 'bit')”

### ISSUE THREAD

**Issue by tytok** [NLua/KeraLua#88]
error:Attempt to read or write to protected memory. This usually indicates that other memory is corrupted.

StackTrace = "   at KeraLua.NativeMethods.luaL_loadbufferx(IntPtr luaState, Byte[] buff, UIntPtr sz, String name, String mode)\r\n   at KeraLua.Lua.LoadBuffer(Byte[] buffer, String name, String mode)\r\n   at KeraLua.Lua.LoadString(String chunk, String name)\r\n   at NL...

**Comment by viniciusjarina** [comment]
Missing info
