### ISSUE TITLE
How to access C # object members from Lua?

### ISSUE THREAD

**Issue by ne-kie** [NLua/KeraLua#89]
How to access C # object members from Lua?

visual studio version: Visual Studio 2022 community
project type: console application
framework: .net 8.0
KeraLua version: 1.4.1

I tried to pass an object from C # to Lua, and when I used Lua's print to print data, I encountered:
userdata: 00000239E12A12C8

And when I tried to access the output field Name, nothing happened, and then the script stopped and continued to execute downwards without any exception messages

my code:
```
            try{
                    using var lua = new Lua();
                    
                    lua.DoString(@"
                            function test(myObj)
                                print(myObj)
                                print(myObj.Name)
                                print(myObj.Age)
                            end
                        ");
                    var myObj = new MyObj()
                    {
                        Name = "allen",
                        Age = 26
                    };
                    
                    lua.GetGlobal("test");
                    lua.PushObject(myObj);
                    lua.PCall(1, 0, 0);
                    lua.Pop(1);
            }
            catch (Exception ex) {
                Console.WriteLine(ex.ToString());
            }
```

please help me, thanks

**Comment by viniciusjarina** [comment]
KeraLua will only provide low-level access similar to what the Lua C API provide. You might want to use NLua instead if you need high-level.

**Comment by ne-kie** [comment]
> KeraLua 仅提供与 Lua C API 提供的类似的低级访问。如果您需要高级访问，则可能需要使用 NLua。

But when I use the NLua library, it encounters Chinese garbled characters. Even if I provide an encoding provider, it only works for Lua's print and other functions. When Lua functions return some Chinese words to C #, C # will receive a question mark "????". How should I handle this?

Not using registered encoding provider and Encoding GetEncoding("GBK").GetBytes, 
can see that the Chinese part is filled with question marks:
![image](https://github.com/user-attachments/assets/c2e7cf8b-9c35-4525-ae84-4fd7f1f5b312)

Use registration code provider and Encoding GetEncoding("GBK").GetBytes, can see that the print part of the Lua function outputs the correct Chinese, while the Chinese passed to C # outputs a question mark:
![image](https://github.com/user-attachments/assets/7f8cda8f-6ba9-42af-a24d-a979702d5005)

my code:
```
            // Registration code provider
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

            using (var lua = new Lua())
            {
                Action<object> action = (o) =>
                {
                    Console.WriteLine("Cecho get param value from lua：" + o);
                };
                lua["Cecho"] = action;

                lua.DoString(Encoding.GetEncoding("GBK").GetBytes(@"
                    print('hell world,你好世界')

                    -- call c# function
                    Cecho('hell world,你好世界')

                    function test(obj)
                        print(obj)
                        print(obj.Name)
                        print(obj.Age)
                    
                        -- return a chinese world

                        return 'hell world,你好世界'
                    end
                "));

                var myObj = new MyObj()
                {
                    Name = "张三",
                    Age = 59
                };

                var result = lua.GetFunction("test").Call(myObj);
                Console.WriteLine(result[0]);
            }
```

**Comment by viniciusjarina** [comment]
You need to set the Encoding properly something like `lua.State.Encoding = Encoding.UTF8;`
